// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockWise.Data;

#nullable disable

namespace StockWise.App.Migrations
{
    [DbContext(typeof(StockDb))]
    [Migration("20260710214746_SeedExtendedData")]
    partial class SeedExtendedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockWise.App.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Электроника",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Бытовая техника",
                            ParentId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Компьютеры",
                            ParentId = 1,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Телефоны",
                            ParentId = 1,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Строительные материалы",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Электрика",
                            ParentId = 5,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Сантехника",
                            ParentId = 5,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Отделочные материалы",
                            ParentId = 5,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "Канцелярия",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "Бумага",
                            ParentId = 9,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ручки",
                            ParentId = 9,
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("StockWise.App.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("INN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactPerson = "Иван Иванов",
                            Email = "info@roznica.ru",
                            INN = "7701234567",
                            Name = "ООО Розница",
                            Phone = "+7 (495) 123-45-67"
                        },
                        new
                        {
                            Id = 2,
                            ContactPerson = "Петр Петров",
                            Email = "info@technomir.ru",
                            INN = "7702345678",
                            Name = "ООО ТехноМир",
                            Phone = "+7 (495) 234-56-78"
                        },
                        new
                        {
                            Id = 3,
                            ContactPerson = "Алексей Сидоров",
                            Email = "sidorov@mail.ru",
                            INN = "7703456789",
                            Name = "ИП Сидоров А.В.",
                            Phone = "+7 (495) 345-67-89"
                        });
                });

            modelBuilder.Entity("StockWise.App.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("FromWarehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StockRefDocId")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("ToWarehouseId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FromWarehouseId");

                    b.HasIndex("ToWarehouseId");

                    b.HasIndex("Type", "Number")
                        .IsUnique();

                    b.ToTable("Documents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            Date = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Number = "IN-2026-0001",
                            Status = "Posted",
                            SupplierName = "ООО Электротех",
                            ToWarehouseId = 1,
                            TotalAmount = 37000m,
                            Type = "Income"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 2,
                            CustomerId = 1,
                            Date = new DateTime(2026, 7, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            FromWarehouseId = 1,
                            Number = "OUT-2026-0001",
                            Status = "Posted",
                            TotalAmount = 9500m,
                            Type = "Outcome"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            Date = new DateTime(2026, 7, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            FromWarehouseId = 1,
                            Number = "TRF-2026-0001",
                            Status = "Draft",
                            ToWarehouseId = 2,
                            TotalAmount = 0m,
                            Type = "Transfer"
                        });
                });

            modelBuilder.Entity("StockWise.App.Models.DocumentLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BatchNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ItemId");

                    b.ToTable("DocumentLines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 7000m,
                            DocumentId = 1,
                            ItemId = 1,
                            Price = 350m,
                            Quantity = 20m
                        },
                        new
                        {
                            Id = 2,
                            Amount = 25000m,
                            DocumentId = 1,
                            ItemId = 2,
                            Price = 2500m,
                            Quantity = 10m
                        },
                        new
                        {
                            Id = 3,
                            Amount = 5000m,
                            DocumentId = 1,
                            ItemId = 8,
                            Price = 500m,
                            Quantity = 10m
                        },
                        new
                        {
                            Id = 4,
                            Amount = 7000m,
                            DocumentId = 2,
                            ItemId = 5,
                            Price = 3500m,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 5,
                            Amount = 2500m,
                            DocumentId = 2,
                            ItemId = 8,
                            Price = 500m,
                            Quantity = 5m
                        },
                        new
                        {
                            Id = 6,
                            Amount = 3500m,
                            DocumentId = 3,
                            ItemId = 1,
                            Price = 350m,
                            Quantity = 10m
                        },
                        new
                        {
                            Id = 7,
                            Amount = 7500m,
                            DocumentId = 3,
                            ItemId = 2,
                            Price = 2500m,
                            Quantity = 3m
                        });
                });

            modelBuilder.Entity("StockWise.App.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalDiff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Inventory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 3,
                            Date = new DateTime(2026, 7, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Number = "INV-2026-0001",
                            Status = "Draft",
                            TotalDiff = -3m,
                            UserId = 3,
                            WarehouseId = 1
                        });
                });

            modelBuilder.Entity("StockWise.App.Models.InventoryLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BatchNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Diff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExpectedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ItemId");

                    b.ToTable("InventoryLine", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActualQty = 28m,
                            Diff = -2m,
                            ExpectedQty = 30m,
                            InventoryId = 1,
                            ItemId = 1,
                            Price = 350m
                        },
                        new
                        {
                            Id = 2,
                            ActualQty = 6m,
                            Diff = 0m,
                            ExpectedQty = 6m,
                            InventoryId = 1,
                            ItemId = 5,
                            Price = 3500m
                        },
                        new
                        {
                            Id = 3,
                            ActualQty = 4m,
                            Diff = -1m,
                            ExpectedQty = 5m,
                            InventoryId = 1,
                            ItemId = 8,
                            Price = 500m
                        });
                });

            modelBuilder.Entity("StockWise.App.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsBatch")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Article")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.ToTable("Items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Article = "HDMI-001",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 50m,
                            MinStock = 5m,
                            Name = "HDMI кабель 3м",
                            Price = 350m,
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 2,
                            Article = "USB-HUB-001",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 20m,
                            MinStock = 2m,
                            Name = "USB-C Hub 7in1",
                            Price = 2500m,
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 3,
                            Article = "BOSCH-T-001",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 10m,
                            MinStock = 2m,
                            Name = "Чайник Bosch TWK7201",
                            Price = 4500m,
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 4,
                            Article = "SAMS-MW-001",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 5m,
                            MinStock = 1m,
                            Name = "Микроволновка Samsung MW3500",
                            Price = 12000m,
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 5,
                            Article = "LOG-KB-001",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 15m,
                            MinStock = 3m,
                            Name = "Клавиатура Logitech K480",
                            Price = 3500m,
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 6,
                            Article = "RAZER-MS-001",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 20m,
                            MinStock = 3m,
                            Name = "Мышь Razer DeathAdder",
                            Price = 2800m,
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 7,
                            Article = "DELL-MON-001",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 5m,
                            MinStock = 1m,
                            Name = "Монитор Dell 27\" S2722QC",
                            Price = 35000m,
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 8,
                            Article = "IP15-CASE-001",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 50m,
                            MinStock = 10m,
                            Name = "Чехол iPhone 15 Pro",
                            Price = 500m,
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 9,
                            Article = "IP15-GLASS-001",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 100m,
                            MinStock = 20m,
                            Name = "Защитное стекло iPhone 15 Pro",
                            Price = 300m,
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 10,
                            Article = "EXT-5M-001",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 30m,
                            MinStock = 5m,
                            Name = "Удлинитель 5м 6 розеток",
                            Price = 850m,
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 11,
                            Article = "LED-12W-001",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = true,
                            MaxStock = 100m,
                            MinStock = 20m,
                            Name = "Лампочка LED 12W",
                            Price = 150m,
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 12,
                            Article = "GROHE-MIX-001",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 10m,
                            MinStock = 2m,
                            Name = "Смеситель Grohe Eurosmart",
                            Price = 3500m,
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 13,
                            Article = "HOSE-1.5-001",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 30m,
                            MinStock = 5m,
                            Name = "Шланг душевой 1.5м",
                            Price = 450m,
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 14,
                            Article = "VETONIT-001",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 30m,
                            MinStock = 5m,
                            Name = "Шпатлёвка Vetonit 5кг",
                            Price = 350m,
                            Unit = "меш"
                        },
                        new
                        {
                            Id = 15,
                            Article = "PAINT-WH-001",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 15m,
                            MinStock = 3m,
                            Name = "Краска белая 3л",
                            Price = 1200m,
                            Unit = "бан"
                        },
                        new
                        {
                            Id = 16,
                            Article = "PAPER-A4-001",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 50m,
                            MinStock = 10m,
                            Name = "Бумага А4 \"Снегурочка\" 500л",
                            Price = 550m,
                            Unit = "пач"
                        },
                        new
                        {
                            Id = 17,
                            Article = "PEN-BLUE-001",
                            CategoryId = 11,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 200m,
                            MinStock = 50m,
                            Name = "Ручка шариковая синяя",
                            Price = 25m,
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 18,
                            Article = "MARKER-BLK-001",
                            CategoryId = 11,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsBatch = false,
                            MaxStock = 100m,
                            MinStock = 20m,
                            Name = "Маркер перманентный чёрный",
                            Price = 85m,
                            Unit = "шт"
                        });
                });

            modelBuilder.Entity("StockWise.App.Models.ItemPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemPrice");
                });

            modelBuilder.Entity("StockWise.App.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 2,
                            CustomerId = 1,
                            Number = "ORD-2026-0001",
                            Status = "New",
                            TotalAmount = 17000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            CustomerId = 2,
                            Number = "ORD-2026-0002",
                            Status = "InProgress",
                            TotalAmount = 8400m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 2,
                            CustomerId = 3,
                            Number = "ORD-2026-0003",
                            Status = "Cancelled",
                            TotalAmount = 1750m
                        });
                });

            modelBuilder.Entity("StockWise.App.Models.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShippedQty")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000m,
                            ItemId = 2,
                            OrderId = 1,
                            Price = 2500m,
                            Quantity = 2m,
                            ShippedQty = 0m
                        },
                        new
                        {
                            Id = 2,
                            Amount = 12000m,
                            ItemId = 4,
                            OrderId = 1,
                            Price = 12000m,
                            Quantity = 1m,
                            ShippedQty = 0m
                        },
                        new
                        {
                            Id = 3,
                            Amount = 8400m,
                            ItemId = 6,
                            OrderId = 2,
                            Price = 2800m,
                            Quantity = 3m,
                            ShippedQty = 0m
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1750m,
                            ItemId = 1,
                            OrderId = 3,
                            Price = 350m,
                            Quantity = 5m,
                            ShippedQty = 0m
                        });
                });

            modelBuilder.Entity("StockWise.App.Models.OutgoingInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("OutgoingInvoice");
                });

            modelBuilder.Entity("StockWise.App.Models.OutgoingLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BatchNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ItemId");

                    b.ToTable("OutgoingLine");
                });

            modelBuilder.Entity("StockWise.App.Models.Reservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("StockBalanceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("StockBalanceId");

                    b.ToTable("Reservations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 7, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 1,
                            Quantity = 2m,
                            Status = "Active",
                            StockBalanceId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 7, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 1,
                            Quantity = 1m,
                            Status = "Active",
                            StockBalanceId = 4L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 2,
                            Quantity = 3m,
                            Status = "Active",
                            StockBalanceId = 6L
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 7, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 3,
                            Quantity = 5m,
                            Status = "Released",
                            StockBalanceId = 1L
                        });
                });

            modelBuilder.Entity("StockWise.App.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Role", "Permission")
                        .IsUnique();

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Permission = "Items.Create",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Permission = "Items.Edit",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Permission = "Items.Delete",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 4,
                            Permission = "Items.View",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 5,
                            Permission = "Warehouse.Create",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 6,
                            Permission = "Warehouse.Edit",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 7,
                            Permission = "Warehouse.View",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 8,
                            Permission = "Documents.Create",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 9,
                            Permission = "Documents.Post",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 10,
                            Permission = "Documents.View",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 11,
                            Permission = "Documents.Cancel",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 12,
                            Permission = "Orders.Create",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 13,
                            Permission = "Orders.Edit",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 14,
                            Permission = "Orders.View",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 15,
                            Permission = "Reports.View",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 16,
                            Permission = "Admin.Users",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 17,
                            Permission = "Items.Create",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 18,
                            Permission = "Items.Edit",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 19,
                            Permission = "Items.View",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 20,
                            Permission = "Documents.Create",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 21,
                            Permission = "Documents.Post",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 22,
                            Permission = "Documents.View",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 23,
                            Permission = "Orders.Create",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 24,
                            Permission = "Orders.Edit",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 25,
                            Permission = "Orders.View",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 26,
                            Permission = "Reports.View",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 27,
                            Permission = "Items.View",
                            Role = "Warehouse"
                        },
                        new
                        {
                            Id = 28,
                            Permission = "Warehouse.View",
                            Role = "Warehouse"
                        },
                        new
                        {
                            Id = 29,
                            Permission = "Documents.View",
                            Role = "Warehouse"
                        },
                        new
                        {
                            Id = 30,
                            Permission = "Inventory.Create",
                            Role = "Warehouse"
                        },
                        new
                        {
                            Id = 31,
                            Permission = "Inventory.Edit",
                            Role = "Warehouse"
                        },
                        new
                        {
                            Id = 32,
                            Permission = "Items.View",
                            Role = "Viewer"
                        },
                        new
                        {
                            Id = 33,
                            Permission = "Warehouse.View",
                            Role = "Viewer"
                        },
                        new
                        {
                            Id = 34,
                            Permission = "Documents.View",
                            Role = "Viewer"
                        },
                        new
                        {
                            Id = 35,
                            Permission = "Reports.View",
                            Role = "Viewer"
                        });
                });

            modelBuilder.Entity("StockWise.App.Models.StockBalance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReservedQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ItemId", "WarehouseId", "BatchNo")
                        .IsUnique()
                        .HasFilter("[BatchNo] IS NOT NULL");

                    b.ToTable("StockBalances", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ItemId = 1,
                            Price = 350m,
                            Quantity = 30m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 2L,
                            ItemId = 2,
                            Price = 2500m,
                            Quantity = 10m,
                            ReservedQty = 2m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 3L,
                            ItemId = 3,
                            Price = 4500m,
                            Quantity = 5m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 4L,
                            ItemId = 4,
                            Price = 12000m,
                            Quantity = 2m,
                            ReservedQty = 1m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 5L,
                            ItemId = 5,
                            Price = 3500m,
                            Quantity = 6m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 6L,
                            ItemId = 6,
                            Price = 2800m,
                            Quantity = 15m,
                            ReservedQty = 3m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 7L,
                            ItemId = 7,
                            Price = 35000m,
                            Quantity = 3m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 8L,
                            ItemId = 8,
                            Price = 500m,
                            Quantity = 5m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 9L,
                            ItemId = 9,
                            Price = 300m,
                            Quantity = 60m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 10L,
                            ItemId = 10,
                            Price = 850m,
                            Quantity = 15m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 11L,
                            BatchNo = "LED-2026-01",
                            ExpiryDate = new DateOnly(2026, 12, 31),
                            ItemId = 11,
                            Price = 150m,
                            Quantity = 50m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 12L,
                            BatchNo = "LED-2026-02",
                            ExpiryDate = new DateOnly(2027, 6, 30),
                            ItemId = 11,
                            Price = 160m,
                            Quantity = 30m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 13L,
                            ItemId = 12,
                            Price = 3500m,
                            Quantity = 4m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 14L,
                            ItemId = 13,
                            Price = 450m,
                            Quantity = 12m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 15L,
                            ItemId = 14,
                            Price = 350m,
                            Quantity = 8m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 16L,
                            ItemId = 15,
                            Price = 1200m,
                            Quantity = 3m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 17L,
                            ItemId = 16,
                            Price = 550m,
                            Quantity = 20m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 18L,
                            ItemId = 16,
                            Price = 520m,
                            Quantity = 30m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 19L,
                            ItemId = 17,
                            Price = 25m,
                            Quantity = 150m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 20L,
                            ItemId = 18,
                            Price = 85m,
                            Quantity = 80m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 21L,
                            ItemId = 1,
                            Price = 350m,
                            Quantity = 20m,
                            ReservedQty = 0m,
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            WarehouseId = 2
                        });
                });

            modelBuilder.Entity("StockWise.App.Models.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RefDocId")
                        .HasColumnType("int");

                    b.Property<string>("RefDocType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("StockBalanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ItemId");

                    b.HasIndex("StockBalanceId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Transactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001L,
                            CreatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Direction = "+",
                            ItemId = 1,
                            Price = 350m,
                            Quantity = 20m,
                            RefDocId = 1,
                            RefDocType = "Income",
                            Type = "Income",
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 1002L,
                            CreatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Direction = "+",
                            ItemId = 2,
                            Price = 2500m,
                            Quantity = 10m,
                            RefDocId = 1,
                            RefDocType = "Income",
                            Type = "Income",
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 1003L,
                            CreatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Direction = "+",
                            ItemId = 8,
                            Price = 500m,
                            Quantity = 10m,
                            RefDocId = 1,
                            RefDocType = "Income",
                            Type = "Income",
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 1004L,
                            CreatedAt = new DateTime(2026, 7, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 2,
                            Direction = "-",
                            ItemId = 5,
                            Price = 3500m,
                            Quantity = 2m,
                            RefDocId = 2,
                            RefDocType = "Outcome",
                            Type = "Outcome",
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 1005L,
                            CreatedAt = new DateTime(2026, 7, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 2,
                            Direction = "-",
                            ItemId = 8,
                            Price = 500m,
                            Quantity = 5m,
                            RefDocId = 2,
                            RefDocType = "Outcome",
                            Type = "Outcome",
                            WarehouseId = 1
                        });
                });

            modelBuilder.Entity("StockWise.App.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Администратор",
                            LastName = "",
                            Login = "admin",
                            PasswordHash = "$2a$10$v7tufXv/BzNs2LFs1YlNX.M6limATLB.C5ZySCXDiK4ev8D/Nu4Qy",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Иван",
                            LastName = "Петров",
                            Login = "manager",
                            PasswordHash = "$2a$10$b/irvmKoiR3SRXJKOFpZUebCb9267sh9lMWDroW1rgtk5T2ByUXlK",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Сергей",
                            LastName = "Иванов",
                            Login = "warehouse",
                            PasswordHash = "$2a$10$aTcj/v7LGvvOc4r1Qs5nqOm7wUMrFKjO4luqNBSfRlU0Ul3uJBcXK",
                            Role = "Warehouse"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Анна",
                            LastName = "Сидорова",
                            Login = "viewer",
                            PasswordHash = "$2a$10$.syaB/VMqXxB.xM8ZF4FBOef/sqnbAuXXLzkXCJZ8pwLm3QJgVI1y",
                            Role = "Viewer"
                        });
                });

            modelBuilder.Entity("StockWise.App.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ул. Ленина, 10",
                            IsActive = true,
                            Name = "Основной склад"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ул. Промышленная, 5",
                            IsActive = true,
                            Name = "Склад №2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "ТЦ \"Гигант\", пав. 12",
                            IsActive = true,
                            Name = "Мелкооптовый"
                        });
                });

            modelBuilder.Entity("StockWise.App.Models.Category", b =>
                {
                    b.HasOne("StockWise.App.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("StockWise.App.Models.Document", b =>
                {
                    b.HasOne("StockWise.App.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockWise.App.Models.Customer", "Customer")
                        .WithMany("Documents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockWise.App.Models.Warehouse", "FromWarehouse")
                        .WithMany()
                        .HasForeignKey("FromWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockWise.App.Models.Warehouse", "ToWarehouse")
                        .WithMany()
                        .HasForeignKey("ToWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("FromWarehouse");

                    b.Navigation("ToWarehouse");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockWise.App.Models.DocumentLine", b =>
                {
                    b.HasOne("StockWise.App.Models.Document", "Document")
                        .WithMany("Lines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockWise.App.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("StockWise.App.Models.Inventory", b =>
                {
                    b.HasOne("StockWise.App.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockWise.App.Models.Warehouse", "Warehouse")
                        .WithMany("Inventories")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockWise.App.Models.InventoryLine", b =>
                {
                    b.HasOne("StockWise.App.Models.Inventory", "Inventory")
                        .WithMany("Lines")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockWise.App.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("StockWise.App.Models.Item", b =>
                {
                    b.HasOne("StockWise.App.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StockWise.App.Models.ItemPrice", b =>
                {
                    b.HasOne("StockWise.App.Models.Item", "Item")
                        .WithMany("Prices")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("StockWise.App.Models.Order", b =>
                {
                    b.HasOne("StockWise.App.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockWise.App.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockWise.App.Models.OrderLine", b =>
                {
                    b.HasOne("StockWise.App.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockWise.App.Models.Order", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("StockWise.App.Models.OutgoingInvoice", b =>
                {
                    b.HasOne("StockWise.App.Models.Customer", "Customer")
                        .WithMany("OutgoingInvoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockWise.App.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockWise.App.Models.OutgoingLine", b =>
                {
                    b.HasOne("StockWise.App.Models.OutgoingInvoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockWise.App.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("StockWise.App.Models.Reservation", b =>
                {
                    b.HasOne("StockWise.App.Models.Order", "Order")
                        .WithMany("Reservations")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockWise.App.Models.StockBalance", "StockBalance")
                        .WithMany("Reservations")
                        .HasForeignKey("StockBalanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("StockBalance");
                });

            modelBuilder.Entity("StockWise.App.Models.StockBalance", b =>
                {
                    b.HasOne("StockWise.App.Models.Item", "Item")
                        .WithMany("StockBalances")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockWise.App.Models.Warehouse", "Warehouse")
                        .WithMany("StockBalances")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockWise.App.Models.Transaction", b =>
                {
                    b.HasOne("StockWise.App.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockWise.App.Models.Item", "Item")
                        .WithMany("Transactions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockWise.App.Models.StockBalance", null)
                        .WithMany("Transactions")
                        .HasForeignKey("StockBalanceId");

                    b.HasOne("StockWise.App.Models.Warehouse", "Warehouse")
                        .WithMany("Transactions")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockWise.App.Models.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("StockWise.App.Models.Customer", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Orders");

                    b.Navigation("OutgoingInvoices");
                });

            modelBuilder.Entity("StockWise.App.Models.Document", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("StockWise.App.Models.Inventory", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("StockWise.App.Models.Item", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("StockBalances");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("StockWise.App.Models.Order", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("StockWise.App.Models.OutgoingInvoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("StockWise.App.Models.StockBalance", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("StockWise.App.Models.User", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("StockWise.App.Models.Warehouse", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("StockBalances");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
